PREFIX cr: <https://w3id.org/cr#>
PREFIX express: <https://w3id.org/express#>
PREFIX ifc: <https://standards.buildingsmart.org/IFC/DEV/IFC4/ADD2/OWL#>

SELECT DISTINCT ?costItem ?geometry ?geometryGlobalId
WHERE {
  ?assign_cost_geom a cr:CostItemToGeometryAssignment ;
                    cr:refCostItem ?costItem ;
                    cr:refGeometry ?geometry .

  OPTIONAL {
    ?geometry ifc:globalId_IfcRoot ?gidNode .
    ?gidNode express:hasString ?geometryGlobalId .
  }
}
ORDER BY ?costItem ?geometry
